### ISSUE TITLE
Error: Unable to resolve module ./index 

### ISSUE THREAD

**Issue by thedf** [microsoft/react-native-gallery#105]
the build doesn't fail on `react-native run-windows`, but it gives the mentioned error below in Metro and doesn't show the app.

```
Error: Unable to resolve module ./index from C:\Users\thedf\Downloads\react-native-gallery-main/.: ./index could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (C:\Users\thedf\Downloads\react-native-gallery-main\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (C:\Users\thedf\Downloads\react-native-gallery-main\node_modules\metro\src\node-haste\DependencyGraph.js:414:43)
    at C:\Users\thedf\Downloads\react-native-gallery-main\node_modules\metro\src\lib\transformHelpers.js:318:42
    at C:\Users\thedf\Downloads\react-native-gallery-main\node_modules\metro\src\Server.js:1471:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\thedf\Downloads\react-native-gallery-main\node_modules\metro\src\Server.js:146:24)
    at _next (C:\Users\thedf\Downloads\react-native-gallery-main\node_modules\metro\src\Server.js:168:9)
```

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`:
5.0.1-alpha.2
2. `npx react-native info`:
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 19.72 GB / 31.90 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\node-v12.18.3-win-x64\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31129.286 (Visual Studio Professional 2019)
  Languages:
    Java: 1.8.0_232 - C:/Program Files/AdoptOpenJDK/jdk-8.0.232.09-openj9/bin/javac.exe
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ^0.64.0-rc.1 => 0.64.0
    react-native-windows: ^0.64.0 => 0.64.2
  npmGlobalPackages:
    *react-native*: Not Found
3.  `npx react-native run-windows --info` : 

 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 19.84 GB / 31.90 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\node-v12.18.3-win-x64\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: ^0.64.0-rc.1 => 0.64.0
    react-native-windows: ^0.64.0 => 0.64.2
  Installed UWP SDKs:
    10.0.14393.0
    10.0.18362.0
    10.0.19041.0

- Target Platform Version(s):
Windows Desktop
- Target Device(s):
 Visual Studio 2019
- Visual Studio Version:
Which build configuration are you running?  Debug

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Clone the repository.
2.In the root directory of the repository on your device, run yarn.
3.In the same directory run `npx react-native run-windows`.

## Expected Results
Exprected to get the app running

**Comment by chiaramooney** [comment]
On my end I'm not able to reproduce your error. When I follow your steps, the app build and runs successfully. Is it possible that you have metro open and running from a different app that you built? Can you check that all instances of chrome debuggers and metro are shut down and then try building again?

**Comment by thedf** [comment]
Each time I do the steps I clear cache close debugger and metro, delete temp files, kill all node instances, delete node_modules and lock file  and run with --reset-cache (sometimes I even reboot my machine). I made sure i have no package installed globally. I honestly don't know why it is not working for me. The only version of react-native-windows that worked for me is 0.61.5. Can you maybe provide me with your environment so I can install the same one ?

**Comment by thedf** [comment]
Update : I upgraded to react 17 and installed Watchman and it runs successfully now. Thanks @chiaramooney for the help !
