### ISSUE TITLE
Links don't have the correct mouse cursor behavior 

### ISSUE THREAD

**Issue by matthidinger** [microsoft/react-native-gallery#106]
![image](https://user-images.githubusercontent.com/1432195/115438431-3f244100-a1c2-11eb-80b3-debcc280841c.png)

The screenshot didn't capture it, but when I mouseover the links at the bottom of a page, such as "Source code" or "Send feedback about this page" I would expect the mouse cursor to be the "hand" and visually indicate this is clickable

**Comment by chiaramooney** [comment]
Current hyperlinks for gallery are built using a Hyperlink component created locally. We should update all of the hyperlinks in the app to use the XAML Hyperlink component via react-native-xaml.
