### ISSUE TITLE
Publish app to App Store

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-gallery#11]
The app is currently not being published to the App Store.  This task is tracking publishing it.

**Comment by kikisaints** [comment]
Could test the app for the windows app certification process (before submission).

**Comment by Poopooracoocoo** [comment]
Are there any RNW apps for Windows 10? This app would be the only one I think and would give people a good feel for it and I'd love to try out a built version.

**Comment by chiaramooney** [comment]
App Published! [Download Here](https://www.microsoft.com/en-us/p/react-native-gallery/9npg0b292h4r?activetab=pivot:overviewtab)

**Comment by Poopooracoocoo** [comment]
@chiaramooney could y'all also make it available for Xbox? And btw was it made by you guys or RN? And how come it took so long?!

**Comment by chrisglein** [comment]
> @chiaramooney could y'all also make it available for Xbox? And btw was it made by you guys or RN? And how come it took so long?!

This was built by the [React Native for Windows](https://github.com/microsoft/react-native-windows) team. And it didn't take _that_ long 😅. Mainly we wanted to make sure there was a good broad control set before publishing this to the store, so we were waiting on some of those to get implemented in their various repos.

As for Xbox, we haven't tested the app to ensure it is accessible only via control pad navigation. It doesn't use a XAML `NavigationView`, for example, but rather the `react-navigation` community module. Not at all impossible, but just something we haven't validated.

**Comment by Poopooracoocoo** [comment]
@chrisglein
okie.

the react-navigation community module is missing hover states btw 😬 probably also missing on android and ios. i'm guessing y'all wanna improve the module or maybe replace it with the xaml control?

it's important that it's available for xbox bc not only is ms already using rnw for the ms store and will probably want more prod rnw apps, but other devs will want to follow suit.

and what happened to skype btw? apparently microsoft is gonna buy discord (and probably ruin it *cough* minecraft *cough*). if skype actually improved it could stand a chance. using rnw would be one 🤣
