### ISSUE TITLE
Simple ScrollView doesn't show text scrollbar

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-gallery#112]
The first ScrollView example shows a scrollbar for the whole page but not for the text in the first example:

![image](https://user-images.githubusercontent.com/22989529/115442703-29654a80-a1c7-11eb-8cf8-960bfa512ab0.png)

**Comment by chiaramooney** [comment]
Investigated this. Looks like the issue is not that the scroll bar is simply cut off. It appears that the behavior of the module is to not display the scroll bar in this case.
