### ISSUE TITLE
Clicking on SensitiveInfo buttons doesn't do anything

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-gallery#113]
Not sure what is supposed to happen but clicking the buttons doesn't seem to do anything

**Comment by chiaramooney** [comment]
@tritao If you have time, can you investigate this?

**Comment by tritao** [comment]
It's a key-value store, so how it should work is that you can set a value in the text box and press the "Set Item" button.
Afterwards pressing the "Get Item" button should retrieve the same value to the text box.

**Comment by asklar** [comment]
ok in that case:
- in the page, the Set should appear before the Get. Maybe we should add a text description of how to use the sample.
- after I Set an item, clicking Get the first time doesn't do anything, it takes a second click of Get to actually get the value back
