### ISSUE TITLE
WebView page hangs for about 10-20s 

### ISSUE THREAD

**Issue by asklar** [microsoft/react-native-gallery#114]
Seems worse on first navigation (the NavView exit animation gets stuck for a while). Seems like something is spinning the UI thread.

**Comment by chiaramooney** [comment]
Interesting. I've definitely experienced maybe a 5 second lag, but not as long as 10-20s. I'll look into it.

**Comment by chiaramooney** [comment]
After working in the WebView repo for a bit, this appears to just be the behavior of loading a native webview.
