### ISSUE TITLE
Enabled a Scaled Back Permissions Page

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-gallery#121]
Currently the permissions page seeks to request almost every permission possible. This causes the app’s appxmanifest to have a ton of capabilities, more than seem necessary. Look into reducing the scope of the permissions that the permissions page is trying to seek. Look into temporarily remove the permissions page entirely.

**Comment by stmoy** [comment]
CC: @tritao - @chiaramooney, the purpose of the Permissions module is to enable the app to _request_ almost every permission possible. However, this has the side effect of exploding the appxmanifest such that it looks like the Gallery _needs_ all of these permissions. 

I wonder if the permissions page itself should list all of the permissions it can support, but the app itself doesn't actually request any more than needed? What is the minimum set of permissions required?

**Comment by chiaramooney** [comment]
@stmoy The minimum capabilities for an RNW app is InternetClient and that's it.

Temporary Removal of Permissions Page: https://github.com/microsoft/react-native-gallery/pull/124
