### ISSUE TITLE
Upgrade to react-native-windows 0.64.4

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/react-native-gallery#122]
Hi,

`react-native-windows` 0.64.4 contains fixes that would allow an updated version of `react-native-sketch-canvas` to work.
After `react-native-gallery` is upgraded to 0.64.4, I'd open a PR to update and enable `react-native-sketch-canvas`.

Thank you.

**Comment by chiaramooney** [comment]
Resolved: https://github.com/microsoft/react-native-gallery/pull/126
