### ISSUE TITLE
Master Task:  Build out of pages for V1 release

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-gallery#14]
The goal of this task is to define the set of pages needed to release v1 of the RN Gallery, announce to the public, and evangelize.

The list only contains the most fundamental controls, to help reduce the time to official V1 announcement.
 
Core Components (has UI)
 - [x] [View](https://reactnative.dev/docs/view)
 - [x] [Image](https://reactnative.dev/docs/image)
 - [x] [Pressable](https://reactnative.dev/docs/pressable)
 - [x] [ScrollView](https://reactnative.dev/docs/scrollview)
 - [x] [Switch](https://reactnative.dev/docs/switch)
 - [x] [Text](https://reactnative.dev/docs/text)
 - [x] [TextInput](https://reactnative.dev/docs/textinput)
 - [x] [FlatList](https://reactnative.dev/docs/flatlist)

 
Community Components (has UI)
 - [x] [Checkbox](https://github.com/react-native-community/react-native-checkbox)
 - [x] [Slider](https://github.com/react-native-community/react-native-slider)
 - [x] [Picker](https://github.com/react-native-community/react-native-picker)
 - [x] [DateTimePicker](https://github.com/react-native-community/datetimepicker)
 - [x] [WebView](https://github.com/react-native-community/react-native-webview)

Windows-only Components (has UI)
 - [x] Popup
 - [x] Flyout

**Comment by chiaramooney** [comment]
Other Pages Added (non UI):
[] Config
[] Device Info

Other Pages Added (UI):
[] Sketch Pad

**Comment by chiaramooney** [comment]
All pages for V1 release have been added!
