### ISSUE TITLE
Page selection list view would benefit from icons

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#168]
Compare the page selection for the XAML controls gallery and the React Native gallery

| XAML Controls Gallery | React Native Gallery |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/26607885/137997838-5c185d32-39b3-45a0-9083-e7e6a592c1b4.png) | ![image](https://user-images.githubusercontent.com/26607885/137997851-32fec189-d84d-4683-b2e8-de2f8f1494dc.png) |

Having icons in this gallery app's list view would make a huge improvement to the experience of finding a page. We can use the same icon assets as exist today in the XAML controls library: https://github.com/microsoft/Xaml-Controls-Gallery/tree/master/XamlControlsGallery/Assets

**Comment by chiaramooney** [comment]
Before I do work on this change, note that gallery gets icons through react-native-xaml right now, so making this change would mean the menu will only work on windows. @chrisglein should I move forward with this work?

**Comment by chrisglein** [comment]
> Before I do work on this change, note that gallery gets icons through react-native-xaml right now, so making this change would mean the menu will only work on windows. @chrisglein Chris Glein FTE should I move forward with this work?

I wasn't thinking this necessarily had to go through the Windows `SymbolIcon` official icon wrapper. A customization of the navigation view list item to add a fixed-size `View` with a background image should suffice.
