### ISSUE TITLE
Current store version on 0.66 lacks Expander page

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#169]
I installed the 0.66.1 version of Gallery and I was expecting to see Expander (#160). But I'm not seeing it in the list. Looks like the release branch missed that commit.

Do we have a release checklist to make it clear which branch the store versions are pulling from?
I'm also noticing we have the app on 0.66 in the store but not here in `main`. I'll open a separate issue for that.

**Comment by chiaramooney** [comment]
Expander now in store!
