### ISSUE TITLE
Add page for *react-native-windows-hello*

### ISSUE THREAD

**Issue by BartoszKlonowski** [microsoft/react-native-gallery#175]
Hello!

What would you say about adding [react-native-windows-hello](https://github.com/callstack/react-native-windows-hello) to this application?
It could be presented just like on the example app with buttons for each feature of this library.

If yes, then would you like to add this page on your own (which would be nice to hear your feedback about it and what are the areas to improve/enhance) or would you like me to implement it (which would save your time of course).

**Comment by chrisglein** [comment]
Does the app do anything with the login information? As in are there considerations for a demo app in handling these credentials in a responsible way?

As for adding it to the app, @chiaramooney do we have a contribution guide for new pages and/or criteria for what cross-platform vs. single-platform (Windows) contributions make the cut?

**Comment by BartoszKlonowski** [comment]
@chrisglein No, the app just returns the result of verification whether user is verified or not. Also the information about biometric device availability does not affect the device itself - only the information with the device status.

**Comment by chiaramooney** [comment]
Yes @chrisglein we have a contribution guide in the README! So far we have been willing to accept both cross-platform and windows only supported modules (such as react-native-xaml). 

@BartoszKlonowski Let's go with the option of you drawing up the sample and I'll be ready to review once you have a PR!
