### ISSUE TITLE
Unable to install dependencies, so cannot run this sample, because some dependecies are broken.

### ISSUE THREAD

**Issue by cangSDARM** [microsoft/react-native-gallery#184]
Some dependecies are broken.

like: `react-native-webview`, there is no `WebViewBridgeComponent` such vscxproj.

![image](https://user-images.githubusercontent.com/20441896/149502083-ae53182b-a50a-4bb1-89de-e72ba46a8214.png)

like: `"react-native-gesture-handler": "JaneaSystems/react-native-gesture-handler.git#windows"`, there are 2 ts error which always trigger the husky check all the time. I cannot install it.

![image](https://user-images.githubusercontent.com/20441896/149503274-4918c6fe-bb0f-4531-8310-18cb4da6e728.png)

**Comment by chrisglein** [comment]
Can you share out the versions for webview and gesture-handler from your package/lock files? There have been same changes in WebView with the bridge and there may be something stale in the solution file.
@chiaramooney check to see if everything's tidy with the autolinking config. And if the version of gesture-handler that gallery consumes has any linting errors.

**Comment by cangSDARM** [comment]
Simply put, I deleted my clone and watched the demo on the windows store. This is a nice project!

As for the version, react-native-window simplifies the structure of the project after 11.15 (see https://github.com/react-native-webview/react-native-webview/pull/2211); and gesture-handler is the latest version (as new as it is now, since its last update was in Mar 2021)

**Comment by chiaramooney** [comment]
Should be resolved now.
