### ISSUE TITLE
Menu bar has coloring issue on certain machines

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-gallery#186]
The Menu Bar has coloring issue (shown below) on certain machines (This repos on my laptop as opposed to my desktop). The blue color will flicker and then stay blue

![image](https://user-images.githubusercontent.com/42554868/151258493-935813e0-259b-45f3-9064-125bf4dbf393.png)

```
systeminfo:
OS Manufacturer:           Microsoft Corporation
OS Version:                10.0.22544 N/A Build 22544
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Product ID:                00330-80000-00000-AA519
System Manufacturer:       LENOVO
System Model:              20T1S02K00
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1502 Mhz
```

**Comment by ShaggyLorean** [comment]
How did you get that build number?

**Comment by asklar** [comment]
for me it does the same thing, but the blue bar flashes. Also using the app from the Store (not rebuilding based on main or anything)
