### ISSUE TITLE
Settings menu is 'pinned' but no visual indicator that it is, resulting in UI that looks broken

### ISSUE THREAD

**Issue by dannyvv** [microsoft/react-native-gallery#188]
I like that the settings menu is 'pinned' in the hamburger menu.
But it is not visually distictive, with either a different background color or a line...
When scrolling the controls list this can make it look like there are rendering issues...
![image](https://user-images.githubusercontent.com/11037542/151422437-48e8d282-f2a8-4415-aabe-f2bc0f85fd99.png)
Especially since the scrollbar is not clearly indicating where the start and stop area's are...

**Comment by chrisglein** [comment]
Agreed. A horizontal divider below the Settings items would help here.
