### ISSUE TITLE
TimePicker example doesn't keep the time that you set from the picker

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#206]
![image](https://user-images.githubusercontent.com/26607885/161812796-4258e105-0d8f-486e-a429-0b12ce95d631.png)

1. Select a time in the picker (other than 12:00 AM)
2. Note that the time in the control has not changed after you close the picker

Version: 1.0.10.0
RNW Version: 0.68.0

**Comment by chrisglein** [comment]
Usage example needs to be updated so it doesn't slam the time value back in.

**Comment by chiaramooney** [comment]
@chrisglein Looking at the page my understanding of the control is that it won't store the time you have selected unless you hit the checkmark in the picker to confirm your selection. Simply clicking outside of the picker will have the same behavior as hitting the 'x' button (effectively cancelling your selection). When I click a time and hit the check button, the time saves, so I don't think a fix is needed here.
