### ISSUE TITLE
Can't build gallery

### ISSUE THREAD

**Issue by dbm5858** [microsoft/react-native-gallery#207]
```
git clone https://github.com/microsoft/react-native-gallery.git
cd react-native-gallery/
npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: rngallery@1.0.5.0
npm ERR! Found: @react-navigation/drawer@"^5.9.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @react-navigation/drawer@"^5.9.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\MeilickD\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MeilickD\AppData\Local\npm-cache\_logs\2022-04-06T14_09_14_456Z-debug-0.log
```

I don't know where to start on this one.  It is totally outside my wheelhouse. 

I cannot install the app from the Microsoft Store, since my company doesn't allow access to the store.

[eresolve-report.txt](https://github.com/microsoft/react-native-gallery/files/8427611/eresolve-report.txt)

[2022-04-06T14_09_14_456Z-debug-0.log](https://github.com/microsoft/react-native-gallery/files/8427603/2022-04-06T14_09_14_456Z-debug-0.log)

**Comment by chiaramooney** [comment]
In gallery we typically use `yarn` instead to handle dependency installation. I would give that a go. Most likely this is an issue that wasn't hit using the yarn pathway but was using npm. I think looking at the package.json I see the issue. I'll make an update soon.

**Comment by dbm5858** [comment]
@chiaramooney 

Hi Chiara,

FYI, I pulled those changes, and it still won't `npm install`.  Same error message. 

I was able to install using `yarn`, though.  So I've got it up and running.  Thanks for that tip.
