### ISSUE TITLE
Explore Updating Component Page Icons

### ISSUE THREAD

**Issue by chiaramooney** [microsoft/react-native-gallery#215]
Currently on the home screen and in the nav drawer there are icons next to each component title. The WinUI Gallery has recently updated its icons. Explore whether this is a change we want to invest in for React Native Gallery. Note this may mean that we chose going down the "Windows" path for main portions of the app i.e. if we want to add Mac support later we would want to make sure the assets are not accessed through react-native-xaml.

**Comment by chrisglein** [comment]
Related to #405 
But specifically, this has been fixed by #414
