### ISSUE TITLE
Tooltip is not defined to expand/collapse button in left navigation pane.

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-gallery#223]
Found during accessibility grading. 

Tracking internal bug: https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/40125135

**Comment by jonthysell** [comment]
XAML can add tooltips almost anywhere: https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.ToolTip?view=winrt-22621

**Comment by jonthysell** [comment]
We could either:

1. Add tooltips everywhere automatically (based on accessibility label?)
2. Expose a property to let devs set/override it
3. Both?
