### ISSUE TITLE
After invoking play button in Track Player page, React Native Gallery app is crashing.

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-gallery#225]
Found during accessibility grading.

Tracking internal bug: https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/40127861

**Comment by AgneLukoseviciute** [comment]
Doesn't repro for me.

**Comment by TatianaKapos** [comment]
@AgneLukoseviciute also doesn't repo for me :(

**Comment by chrisglein** [comment]
0/3 on reproing it... can someone check if this repro'd during the second accessibility grading pass?

**Comment by AgneLukoseviciute** [comment]
A11y testing team wasn't able to reproduce on the newer build either & closed out the ADO bug.
