### ISSUE TITLE
Add RN Gallery to manual checklist for cutting RNW releases

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-gallery#23]
We can use the gallery app to validate the quality of RNW major releases.
Nick Gerleman is driving overall release quality/schedule, need to coordinate with him.

Rough outline of steps:
1) Update RN Gallery to target latest RNW
  1a) May require updating community modules
2) Run through the pages and validate they still work

**Comment by kmelmon** [comment]
Conversation ongoing, now have a branch for 0.64 release.  @chiaramooney can you verify with Nick that we can have validation become a checkbox in the validation doc if one exists?

**Comment by chiaramooney** [comment]
Confirmed with Nick that validation using RNGallery is now on the list of todos for every major release (i.e. 0.64 to 0.65). Nick will let me know when a release is happening and a preview of the new release is ready. Then I'll upgrade RNGallery to that preview on a branch, validate that all of the pages are rendering correctly and no modules are broken, and report back to him.
