### ISSUE TITLE
Add TouchableWithoutFeedback Example page

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/react-native-gallery#257]
We don't currently have an example page for `TouchableWithoutFeedback` in gallery... we should add it 😊

**Comment by chrisglein** [comment]
There has been motion towards 'Pressable' as the replacement. However there is a lot of existing use of 'TouchableWithoutFeedback', so we want to ensure that it works correctly. So as a test case, this is a good idea. As a recommendation for "Do it this way", not so much.

**Comment by TatianaKapos** [comment]
Adding a banner comment redirecting to Pressable is a good idea! This page can be pretty simple since it's mostly as a testcase, may want to start this page by basing it off the 'Pressable' page.
