### ISSUE TITLE
Blank screen on debug build.

### ISSUE THREAD

**Issue by cjhines** [microsoft/react-native-gallery#262]
I cloned the app fresh just to make sure I wasn't missing anything.

1. `yarn`
2. `npx react-native run-windows --logging` 

Is there a way to get native output? Debugger console offers no hints, just warnings:

```
Require cycle: src\RNGalleryList.ts -> src\HomePage.tsx -> src\RNGalleryList.ts
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
```

<img width="500" alt="Screenshot 2022-08-15 at 17 44 49" src="https://user-images.githubusercontent.com/16542421/184668451-ae9f80fb-0512-49cf-8e4d-0df384540467.png">

`npx react-native --version` output:
```
8.0.3
```

`npx react-native info` output:
```
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 7.41 GB / 15.99 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: ^0.69.0 => 0.69.1
    react-native-windows: 0.69.0 => 0.69.0
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by cjhines** [comment]
Release build works, however.

<img width="500" alt="Screenshot 2022-08-16 at 10 05 44" src="https://user-images.githubusercontent.com/16542421/184829786-d2bb7b02-fc6a-44bd-bdfb-f37b5d659c50.png">

**Comment by AgneLukoseviciute** [comment]
@cjhines, could you try closing out the chrome debugger between runs and see if that fixes it? I ran into this recently and that fixed it for me.
