### ISSUE TITLE
Build React Native Gallery on your Mac computer locally  ?

### ISSUE THREAD

**Issue by whoami-shubham** [microsoft/react-native-gallery#268]
is this project meant to be built on Windows computers only? 
I tried building using the command `npx react-native run-windows` also tried `yarn android` on Mac

using `yarn android` command this task failed while building
```
 Task :react-native-safe-area-context:compileDebugKotlin
 
```

**Comment by asklar** [comment]
RN Windows app can only be built on Windows devices
