### ISSUE TITLE
Add Keyboard rich experience

### ISSUE THREAD

**Issue by gabimoncha** [microsoft/react-native-gallery#278]
Although this is documented, it seems the website is outdated because I wasn't able to implement this feature.
https://microsoft.github.io/react-native-windows/docs/ikeyboardprops-api

**Comment by jonthysell** [comment]
@chiaramooney Can you look into the docs and what gallery is doing and see if there's a disconnect?

**Comment by chiaramooney** [comment]
Gallery does not make use of this API. @gabimoncha. If you run the Playground app in the react-native-windows repo and load the rntester bundle there should be examples there of how to use the API. If you are still hitting issues getting this API to work please file a bug on our documentation repo react-native-windows-samples or our main repo react-native-windows.
