### ISSUE TITLE
Gallery has additional unstated tool dependencies beyond building a vanilla RNW app

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#298]
Upon cloning gallery and building for the first time, I've hit the following requirements that are beyond what is covered in [RNW Dependencies](https://microsoft.github.io/react-native-windows/docs/rnw-dependencies):
```
Time Elapsed 00:00:04.65
√ Restoring NuGet packages
 √ Auto-linking...
Success: No auto-linking changes necessary. (979ms)
 √ Found Solution: C:\Users\asdf\Source\react-native-gallery\windows\rngallery.sln
 i Build configuration: Debug
 i Build platform: x64
× Building Solution: ReactNativeExpander.vcxproj -> C:\Users\asdf\Source\react-native-gallery\windows\x64\Debu...
× Build failed with message 7:10>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\asdf\Source\react-native-gallery\node_modules\@react-native-community\checkbox\windows\CheckboxWindows\CheckboxWindows.vcxproj].
```
Solution: Launch Visual Studio Installer, choose VS installation, select "Modify", "Individual Components", search for 10.0.18362.0 SDK, install.

```
Time Elapsed 00:00:01.86
√ Restoring NuGet packages
 √ Auto-linking...
Success: No auto-linking changes necessary. (2870ms)
 √ Found Solution: C:\Users\asdf\Source\react-native-gallery\windows\rngallery.sln
 i Build configuration: Debug
 i Build platform: x64
 × Building Solution: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.X...
 × Build failed with message 20:10>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(443,5): error MSB8020: The build tools for 'v140' application Type UWP (Platform Toolset = 'Visual Studio 2015') cannot be found. Please install the workflow for this application type and include the build tools for the  [C:\Users\asdf\Source\react-native-gallery\node_modules\@react-native-clipboard\clipboard\windows\Clipboard\Clipboard.vcxproj]. Check your build configuration.
Command failed. Re-run the command with --logging for more information.
```
Specifically it's the Clipboard and progress-view projects that have the older toolset.
Solution: Launch Visual Studio Installer, choose VS installation, select "Modify", "Individual Components", search for "v140", install.
OR, go patch up Clipboard and progress-view:
![image](https://user-images.githubusercontent.com/26607885/216671363-de228319-0393-4f61-86f3-b6a081c17210.png)

**Comment by chrisglein** [comment]
If you patch up Clipboard and progress-view, you'll be left with another build error:
```
Time Elapsed 00:00:01.72
√ Restoring NuGet packages
 √ Auto-linking...
Success: No auto-linking changes necessary. (2739ms)
 √ Found Solution: C:\Users\asdf\Source\react-native-gallery\windows\rngallery.sln
 i Build configuration: Debug
 i Build platform: x64
 × Building Solution: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.X...
 × Build failed with message 24:10>C:\Users\asdf\Source\react-native-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\JSI\JsiAbiApi.h(271,28): error C4996: 'std::aligned_storage_t': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to suppress this warning. (compiling source file C:\Users\asdf\Source\react-native-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\TurboModuleProvider.cpp) [C:\Users\asdf\Source\react-native-gallery\node_modules\react-native-xaml\windows\ReactNativeXaml\ReactNativeXaml.vcxproj]. Check your build configuration.
Command failed. Re-run the command with --logging for more information.
```

error C4996: 'std::aligned_storage_t': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to suppress this warning. (compiling source file C:\Users\asdf\Source\react-native-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\TurboModuleProvider.cpp)

**Comment by chrisglein** [comment]
> If you patch up Clipboard and progress-view, you'll be left with another build error:
> 
> ```
> error C4996: 'std::aligned_storage_t': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to suppress this warning. (compiling source file C:\Users\asdf\Source\react-native-gallery\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\TurboModuleProvider.cpp)

Workaround:
```node_modules\react-native-xaml\windows\ReactNativeXaml\ReactNativeXaml.vcxproj:      <LanguageStandard Condition="'$(Configuration)|$(Platform)'=='Debug|ARM'">stdcpplatest</LanguageStandard>```
Replace all instances of `stdcpplatest` with `stdcpp20`

**Comment by chrisglein** [comment]
A couple changes here:
- Change Clipboard to not require v140
- Change progress-view to not require v140
- Update react-native-xaml to align on cpp version and/or address https://github.com/microsoft/react-native-windows/issues/10390

Not sure what is requiring this SDK version (specific module, or something within gallery): 10.0.18362.0. But that needs investigating.

**Comment by jonthysell** [comment]
Gallery should target a newer version of RNX where the stdcpp20 fix has already been applied. In fact gallery should update to the new version of RNX after https://github.com/microsoft/react-native-xaml/pull/238 gets merged.

**Comment by TatianaKapos** [comment]
closing via https://github.com/microsoft/react-native-gallery/pull/304 and https://github.com/microsoft/react-native-gallery/pull/343. Tested on Gallery and it's building fine without any changes :)
