### ISSUE TITLE
[React Native Gallery]: The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by YajurG** [microsoft/react-native-gallery#336]
**Repro-Steps:**
Launch the React Native Gallery app.
Navigate to ‘DatePicker’ button using tab key and invoke it.
Now run fastpass and observe. 

**Actual Result:**
The Name property of a focusable element must not be null. 
 
**Expected Result:**
The Name property of a focusable element must be defined. 

**User impact:**
Users with visual impairments who rely on screen reader will not be able to know the name and purpose of the button if they is not proper name is defined. 

Internal bug link: https://microsoft.visualstudio.com/OS/_workitems/edit/45264469

**Comment by chrisglein** [comment]
DatePicker doesn't support the accessibility label, but we can create a PR on that repo to add it and then take the updated dependency on the app side.
