### ISSUE TITLE
add lottie animations

### ISSUE THREAD

**Issue by Victor0814gui** [microsoft/react-native-gallery#341]
I would like to see examples of lottie animations in the gallery. I would like to add this feature :)

**Comment by chrisglein** [comment]
We [added Windows support](https://github.com/microsoft/react-native-windows/issues/3278) for [Lottie](https://github.com/lottie-react-native/lottie-react-native) and got it merged over a year ago. Lottie animations are a popular way to add rich animations, and seem like a good candidate for a sample in the gallery app. If I recall there are two paths: either runtime loading of Lottie animations, or use of codegen to create C++Windows Composition calls to Lottie that are highly optimized. The former is more inline with the cross-platform approach to Lottie, whereas the latter is the best for performance.

@victor0814gui, glad to hear you'd be willing to make a contribution to gallery to add a page showing usage of lottie animations. We would accept a PR with that. You have any more in mind?

Contribution guide here: https://github.com/microsoft/react-native-gallery/wiki/Contributing-to-React-Native-Gallery

FYI to @chiaramooney and @jonthysell in case they have anything to add about requirements a new gallery page would need to meet and/or considerations for Lottie specifically.

**Comment by Victor0814gui** [comment]
Thanks for the reply. I would also like to add the @react-native-community/netinfo and react-native-svg packages.
