### ISSUE TITLE
Update gallery to RNW 0.64 release

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#38]
RNW is currently previewing the 0.64 release. As of right now the 5th preview us up:
- [react-native-windows_v0.64.0-preview.5](https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.64.0-preview.5)

It would be useful to validate the 0.64 previews with this gallery app (see issue #23). Let's get a build of gallery on 0.64 ready so we can start testing it.

**Comment by chiaramooney** [comment]
See branch 'v0.64.0-preview.5' for version of app with RNW v0.64.0-preview.5

**Comment by chrisglein** [comment]
0.64 is finally released so we should update from preview and merge that branch to main.
