### ISSUE TITLE
Add Home page with all planned components

### ISSUE THREAD

**Issue by Yajur-Grover** [microsoft/react-native-gallery#396]
Update the Gallery Fabric application home page to have buttons for all planned components - similar to the current home page of Gallery - but have the buttons for components that are not currently implemented be greyed out/disabled.

**Comment by chrisglein** [comment]
Add a tasklist on this issue of the items that are missing?

**Comment by Yajur-Grover** [comment]
I believe this issue was created before there was any home page at all - since there is a homepage that exists on the new Gallery-Fabric app, closing this as completed for now. If there are any further components that need to be added to the home page, we can create a separate issue or task on the parent tracking issue accordingly.
