### ISSUE TITLE
Community Module info button not legible in dark theme

### ISSUE THREAD

**Issue by marcelwgn** [microsoft/react-native-gallery#402]
The button/text indicating a control is provided through a community module is hardly legible in dark theme:
![Screenshot of React Native Gallery where the top right button indicating the control being a community control is using light text on light background](https://github.com/microsoft/react-native-gallery/assets/16122379/e6a8c07f-0962-4f26-8781-fcf1c76af462)

**Comment by jonthysell** [comment]
This appears to be a duplicate of #381.
