### ISSUE TITLE
Provide capabilities similar to Canvas.

### ISSUE THREAD

**Issue by annpeter** [microsoft/react-native-gallery#449]
Provide capabilities similar to Canvas. It can draw images and various shapes.

**Comment by jonthysell** [comment]
Is there a particular module you think should be in Gallery? There is a `react-native-sketch-canvas` in the Gallery already.

**Comment by annpeter** [comment]
react-native-sketch-canva can't draw images.

**Comment by chrisglein** [comment]
> react-native-sketch-canva can't draw images.

Can you provide more detail in your scenario? Is there a cross-platform library from the [directory](https://reactnative.directory/) that captures what you're looking for?
