### ISSUE TITLE
Create list of manual verification steps

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#48]
Related issue: https://github.com/microsoft/react-native-windows/issues/5326

We'd like to use this Gallery app as a tool for validating RNW releases. This can involve visiting a list of pages and doing certain operations on each page to ensure the UI is working as expected. This isn't a complete answer, and automated verification is definitely where we want to save more time on manual process, but having a manual list is a good start. That's the first step.

**Comment by chiaramooney** [comment]
Created a wiki page in the RN Gallery Repo containing a draft of the steps to validate releases with RN Gallery.
Page linked here: https://github.com/microsoft/react-native-gallery/wiki/Manual-Validation-Steps-for-RNW-Release
