### ISSUE TITLE
CI is failing due to running out of disk space

### ISSUE THREAD

**Issue by tritao** [microsoft/react-native-gallery#49]
As the title says, the CI is currently failing on two open PRs due to running out of disk space:

https://github.com/microsoft/react-native-gallery/pull/27
https://github.com/microsoft/react-native-gallery/pull/46

The error: `You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 0 MB`

Github Actions runners only guarantee 14GB of disk space: https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

A potential solution is probably so setup a Gallery-specific Actions runner (on Azure for instance).

**Comment by chiaramooney** [comment]
Working on this now with @kmelmon to get a VM with larger capacity. Will update soon with plan of action.
