### ISSUE TITLE
Bug 54111681: [React Native Gallery -> ProgressView]: The Name property of a focusable element is null.

### ISSUE THREAD

**Issue by Yajur-Grover** [microsoft/react-native-gallery#505]
Build Details:
OS Version: Dev (OS Build 27695.1000)
App: React Native Gallery 
App Version: 1.0.18.0
React Native Windows Version: 0.75.0
AT: Fast Pass
 
Repro-Steps:
Launch the React Native Gallery app.
Navigate to ‘All samples’ button present in left navigation pane and invoke it.
Navigate to 'ProgressView’ button present under “Basic Input” group and invoke it.
Now run fast pass and observe the issue.
Actual Result:
The Name property of a focusable element is null.

Expected Result:
The Name property of a focusable element must not be null.

User Impact:
Users with visual impairment who rely on screen reader will be misguided if narrator announces incorrect control type of the item.
 
Link to ADO bug: https://dev.azure.com/microsoft/OS/_workitems/edit/54111681

**Comment by chrisglein** [comment]
Accessibility name is applied but doesn't seem to be being passed through. Need to see if there's a platform issue on this one.

**Comment by Yajur-Grover** [comment]
Resolved in the following: https://github.com/react-native-progress-view/progress-view/pull/144. The fix has just been published in latest - will bump Gallery to include the change.
