### ISSUE TITLE
Accessing the Permissions page crashes the app

### ISSUE THREAD

**Issue by rectified95** [microsoft/react-native-gallery#62]
As in the title. Looking at the callstack, I'm hitting an unhandled exception at RNPermissions.cpp@64
Could be the gallery app is missing some app manifest attributes, compared to the example one in the RNPermissions repo.

**Comment by kmelmon** [comment]
@tritao we're seeing crashes with this sample page.  Can you take a look?

**Comment by tritao** [comment]
I will check what's going on.

**Comment by chiaramooney** [comment]
The CI Loop is currently producing this error: 

error MSB3271: There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture, "AMD64", of the implementation file "C:\Users\chiaramooney\Documents\Code\react-native-gallery\node_modules\react-native-windows\target\x64\Release\Microsoft.ReactNative\Microsoft.ReactNative.dll" for "C:\Users\chiaramooney\Documents\Code\react-native-gallery\node_modules\react-native-windows\\target\x64\Release\Microsoft.ReactNative\Microsoft.ReactNative.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project. [C:\Users\chiaramooney\Documents\Code\react-native-gallery\node_modules\react-native-permissions\windows\RNPermissions\RNPermissions.vcxproj]. Check your build configuration.

Could this be connected to this issue?

**Comment by tritao** [comment]
I don't think its related, I already have a fix for this issue and will open a PR in a bit. We can check the CI then.
