### ISSUE TITLE
Try to target WinUI 2.6 prerelease

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-gallery#76]
Let's not push this to `main` until 2.6 is mature. But we should see if there are any issues targeting WinUI 2.6 and start playing around with that build.

https://www.nuget.org/packages/Microsoft.UI.Xaml/2.6.0-prerelease.210217002

**Comment by chiaramooney** [comment]
Branch now running on 2.6 Prerelease here: https://github.com/chiaramooney/react-native-gallery/tree/xaml-2.6

Currently have a branch of Gallery running on WinUI 2.6.0-prerelease.210129001. This is not the latest WinUI 2.x version but versions higher than this one fail with a series of error stating that the package cannot be found (currently investigating why this is the case). It appears that the styling of react-native-xaml controls is being updated with the update to WinUI 2.6 prerelease. However, I need to investigate to see that the styling progress that is visible in the gallery contains all the styling updates for that release and no styling updates are being ignored.
