### ISSUE TITLE
fix auto-linking of checkbox

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-gallery#9]
When we upgraded to 0.63, we were unable to get auto-linking working for the @react-native-community/checkbox module.  

To remove the manual linking I did this:

remove:
    PackageProviders().Append(winrt::CheckboxWindows::ReactPackageProvider());
from App.cpp

This generated a redbox error.  Probably need help from @jonthysell to figure this one out.

**Comment by kmelmon** [comment]
@jonthysell we're seeing more modules being added to the app and they're all doing the same workaround.  If you can shed some light on this that would be great.

**Comment by kikisaints** [comment]
We may need to upgrade to 0.64 to get this correct.

**Comment by kmelmon** [comment]
Does this change fix things?
https://github.com/microsoft/react-native-windows/pull/6420

**Comment by chiaramooney** [comment]
Checkbox now supports autolinking.
